#!/usr/bin/env bash
# Supervisor program: serve the headless sway output over VNC on :5900.
#
# Replaces the entrypoint's previous `x11vnc -display :0 ...` line.
# Waits for sway to publish its Wayland socket before launching — wayvnc
# connects as a Wayland client and can't bootstrap before the compositor.
set -euo pipefail

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-root}"
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-1}"

# Block until the sway socket exists. supervisor's startretries=10 catches
# the case where sway is slow to come up after a restart.
for _ in $(seq 1 60); do
  if [[ -S "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" ]]; then
    break
  fi
  sleep 0.5
done

if [[ ! -S "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" ]]; then
  echo "wayvnc: Wayland socket $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY never appeared" >&2
  exit 1
fi

# Listen on all interfaces, port 5900 — pulled from /opt/obs/config/
# wayvnc.cfg along with the VeNCrypt TLS settings. The self-signed
# cert + key are generated by entrypoint.sh per pod start (paths in
# the cfg file point at $XDG_RUNTIME_DIR/wayvnc.{key,crt}). VeNCrypt
# is what macOS Screen Sharing.app prefers; wayvnc's default "None
# only" offering caused Screen Sharing to refuse the connection with
# "Unable to communicate with localhost". relax_encryption=true keeps
# the "None" path available too for less-capable clients.
exec wayvnc --config=/opt/obs/config/wayvnc.cfg
