---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: tripbot
  name: tripbot
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: tripbot-server

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripbot
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tripbot
          servicePort: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: tripbot-metrics
  name: tripbot
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  selector:
    matchLabels:
      k8s-app: tripbot
