[program:browser-refresh]
command=/opt/obs/script/start-browser-refresh.sh
priority=40
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
