---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs
spec:
  template:
    spec:
      containers:

      - name: obs
        imagePullPolicy: Always
        # command:
        #  - bash
        # args:
        #  - -c
        #  - sleep 600
        env:
         - name: ENV
           value: "stage"
         - name: VLC_SERVER_HOST
           value: "http://localhost"
         - name: MPD_SERVER_HOST
           value: "localhost:6600"
         # - name: VNC_PASSWORD
         #   value: "testme"

        volumeMounts:
        # mount stage-dotenv volume to /opt/tripbot
        - name: stage-dotenv
          mountPath: /opt/tripbot/.env.staging
          readOnly: true
          subPath: .env.staging

      volumes:
      - name: stage-dotenv
        configMap:
          name: stage-dotenv
          items:
            - key: stage-dotenv
              path: .env.staging
