version: '3.7'

services:
  tripbot:
    environment:
      ENV: production
      GOOGLE_APPLICATION_CREDENTIALS: /opt/tripbot/infra/google/tripbot-prod.json
      DISABLE_TWITCH_WEBHOOKS: "false"
    ports:
      - "8080:8080"
    env_file:
      - ./.env.production
    entrypoint: bash
    command: -c "go run cmd/tripbot/tripbot.go 2>&1"
    depends_on: {}
    restart: always
