version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  obs:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    entrypoint: "true"
    restart: on-failure

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
