version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    entrypoint: bash
    command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  obs:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    # comment this to enable obs container
    # entrypoint: "true"
    restart: on-failure

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
