version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
      DISABLE_WEBHOOKS: "true"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/tripbot/infra/google/tripbot-stage.json
    env_file:
      - ./.env.development
    #TODO: add apt update, apt install -y postgresql vim
    #TODO: add dir in this repo with scripts intended to be run in docker
    # command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  vlc-server:
    environment:
      ENV: development
      VDPAU_DRIVER: nvidia
      DISABLE_OBS: "${DISABLE_OBS}"
      # AWS_REGION: "${AWS_REGION}"
      # AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      # AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      # AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      # VLC_VERBOSE: "true"
      # DISABLE_OBS: "true"
    env_file:
      - ./.env.development
    # set this to true to disable the OBS container
    #entrypoint: "true"
    restart: on-failure
    entrypoint: bash
    command: -c "cd /opt/tripbot && rm -f bin/vlc-server && script/container_startup.sh"
    volumes:
      - .bash_history.remote:/root/.bash_history

  db:
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
