version: '3.7'

services:
  tripbot:
    # these are set at the github level:
    # https://github.com/dmerrick/tripbot/settings/secrets/new
    environment:
      - CHANNEL_NAME
      - BOT_USERNAME
      - TWITCH_AUTH_TOKEN
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET

  obs:
    environment:
      - CHANNEL_NAME
      #TODO: almost none of these are actually required by OBS
      - BOT_USERNAME
      - TWITCH_AUTH_TOKEN
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
