version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    entrypoint: bash
    command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  obs:
    environment:
      ENV: development
      # VLC_VERBOSE: "true"
      # DISABLE_OBS: "true"
    env_file:
      - ./.env.development
    # comment this to enable obs container
    #entrypoint: "true"
    restart: on-failure
    entrypoint: bash
    command: -c "cd /opt/tripbot && rm -f bin/vlc-server && script/container_startup.sh"
    # command: -c "go run cmd/vlc-server/vlc-server.go 2>&1"
    volumes:
      - /home/dmerrick/Videos/Dashcam/screencaps:/opt/data/screencaps:ro
      # I had to include this to overwrite the volume set in the base file
      - /home/dmerrick/Videos/Dashcam/_all:/opt/data/Dashcam/_all:ro
      # - /tmp/.X11-unix:/tmp/.X11-unix

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

# networks:
#   tripbot_default:
#     external: true
