version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
      DISABLE_WEBHOOKS: "true"
    env_file:
      - ./.env.development
    # command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  onscreens-server:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
