version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
      DISABLE_WEBHOOKS: "true"
    env_file:
      - ./.env.development
    #TODO: add apt update, apt install -y postgresql vim
    #TODO: add dir in this repo with scripts intended to be run in docker
    # command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  vlc:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    volumes:
      - .bash_history.remote:/root/.bash_history

  onscreens-server:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
