version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    env_file:
      - ./.env.development
    entrypoint: bash
    command: -c "go run cmd/tripbot/tripbot.go 2>&1"

  obs:
    environment:
      ENV: development
      DISPLAY: ":0.0"
      FONTCONFIG_PATH: /etc/fonts
    env_file:
      - ./.env.development
    # comment this to enable obs container
    #entrypoint: "true"
    restart: on-failure
    # entrypoint: bash
    # command: -c "go run cmd/vlc-server/vlc-server.go 2>&1"
    volumes:
      - /home/dmerrick/Videos/Dashcam/_all:/opt/data/Dashcam/_all:ro

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

networks:
  tripbot_default:
    external: true
