version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    #TODO: do we need this if we use a volume?
    # env_file:
    #   - ./.env.development
    volumes:
      - ./.env.development:/danalol/.env.development

  vlc:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
