version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  vlc:
    environment:
      ENV: development
    env_file:
      - ./.env.development

  db:
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
