version: '3.7'

services:
  tripbot:
    # these are set at the github level:
    # https://github.com/adanalife/tripbot/settings/secrets/new
    environment:
      - CHANNEL_NAME
      - BOT_USERNAME
      - TWITCH_AUTH_TOKEN
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
    build:
      # pull down cache layers from repo
      cache_from:
        - adanalife/tripbot

  vlc-server:
    build:
      # pull down cache layers from repo
      cache_from:
        - adanalife/vlc-server
