version: '3.7'

services:
  tripbot:
    environment:
      ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: /opt/tripbot/infra/google/tripbot-stage.json
    env_file:
      - ./.env.development
    entrypoint: bash
    command: -c "go run cmd/tripbot/tripbot.go 2>&1"
    volumes:
      # - /home/dmerrick/Videos/Dashcam/screencaps:/opt/data/screencaps:ro
      - "/Volumes/Leeroy/Dana's Photos/Dashcam Scratchpad/Dashcam/screencaps:/opt/data/screencaps:ro"

  obs:
    environment:
      ENV: development
      VDPAU_DRIVER: nvidia
      DISABLE_OBS: "${DISABLE_OBS}"
      # AWS_REGION: "${AWS_REGION}"
      # AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      # AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      # AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      # VLC_VERBOSE: "true"
      # DISABLE_OBS: "true"
    env_file:
      - ./.env.development
    # set this to true to disable the OBS container
    #entrypoint: "true"
    restart: on-failure
    entrypoint: bash
    command: -c "cd /opt/tripbot && rm -f bin/vlc-server && script/container_startup.sh"
    volumes:
      - .bash_history.remote:/root/.bash_history
      - /Volumes/Leeroy/Dana\'s\ Photos/Dashcam\ Scratchpad/Dashcam/screencaps:/opt/data/screencaps:ro
      - /Volumes/Leeroy/Dana\'s\ Photos/Dashcam\ Scratchpad/Dashcam/_all:/opt/data/Dashcam/_all:ro
      # - /home/dmerrick/Videos/Dashcam/screencaps:/opt/data/screencaps:ro
      # - /home/dmerrick/Videos/Dashcam/_all:/opt/data/Dashcam/_all:ro

  vlc:
    privileged: true
    image: adanalife/obs
    hostname: obs
    env_file:
      - infra/docker/env.docker
    build:
      context: .
      dockerfile: infra/docker/obs/Dockerfile
    ports:
      # this should match the VLC_SERVER_HOST env var
      - "8080"
      - "5902:5900"
    environment:
      DISABLE_OBS: "true"
      ENV: development
      DISPLAY: ":0.0"
      XDG_RUNTIME_DIR: "/root/.cache/xdgr"
      # hack to make fontconfig happy
      FONTCONFIG_PATH: "/etc/fonts"
      STREAM_KEY: "${STREAM_KEY}"
    volumes:
      - .bash_history.remote:/root/.bash_history
      - .:/go/src/github.com/adanalife/tripbot
      - /Volumes/Leeroy/Dana\'s\ Photos/Dashcam\ Scratchpad/Dashcam/screencaps:/opt/data/screencaps:ro
      - /Volumes/Leeroy/Dana\'s\ Photos/Dashcam\ Scratchpad/Dashcam/_all:/opt/data/Dashcam/_all:ro
    restart: unless-stopped

  db:
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
