"""External Secrets Operator CR builders.

cdk8s *emits the CRs*; ESO does the materialization. ExternalSecret is emitted
via the **typed** construct generated by `cdk8s import` from the vendored CRD
(imports.io.external_secrets) — see cdk8s.yaml. Three ExternalSecret shapes are
covered here:

  1. `dataFrom.extract`  — pull every top-level key of a JSON parameter value
     into the Secret (grafana OTLP, sentry, postgres). `extract=<parameter>`.
  2. per-key `remoteRef` + `property` — map specific JSON properties of a
     parameter to named Secret keys (cert-manager creds).
     `data=[ESData(secret_key, key, property)]`.
  3. bare `remoteRef` — one parameter → one Secret key (obs stream-key).
     `data=[ESData(secret_key, key)]`.

The keybase-bootstrapped `eso-aws-credentials` Secret lives outside cdk8s —
cdk8s never creates it; the SecretStore just references it by name.
"""

from __future__ import annotations

from dataclasses import dataclass

from constructs import Construct

import imports.io.external_secrets as esx

# The store every app ExternalSecret references — namespaced, identical in
# every env (isolation is structural: a namespaced store is unreachable
# cross-namespace; the backing eso-aws-credentials decides the AWS account).
DEFAULT_STORE = ("aws-parameterstore", "SecretStore")

_STORE_KIND = {
    "SecretStore": esx.ExternalSecretSpecSecretStoreRefKind.SECRET_STORE,
    "ClusterSecretStore": esx.ExternalSecretSpecSecretStoreRefKind.CLUSTER_SECRET_STORE,
}
_CREATION_POLICY = {
    "Owner": esx.ExternalSecretSpecTargetCreationPolicy.OWNER,
    "Merge": esx.ExternalSecretSpecTargetCreationPolicy.MERGE,
    "None": esx.ExternalSecretSpecTargetCreationPolicy.NONE,
    "Orphan": esx.ExternalSecretSpecTargetCreationPolicy.ORPHAN,
}


@dataclass(frozen=True)
class ESData:
    """One entry in an ExternalSecret `spec.data[]`."""

    secret_key: str  # key in the materialized Secret
    key: str  # SSM parameter path
    property: str | None = None  # JSON property within the value (pattern 2)


def external_secret(
    scope: Construct,
    id: str,
    *,
    name: str,
    namespace: str | None = None,
    refresh: str = "1h",
    store: tuple[str, str] = DEFAULT_STORE,
    target_name: str | None = None,
    creation_policy: str | None = None,
    labels: dict[str, str] | None = None,
    extract: str | None = None,
    data: list[ESData] | None = None,
):
    """Emit one ExternalSecret (typed construct). Supply exactly one of `extract`
    (pattern 1) or `data` (patterns 2/3). `target_name` defaults to `name`."""
    if (extract is None) == (data is None):
        raise ValueError("external_secret: pass exactly one of extract= or data=")

    meta: dict = {"name": name}
    if namespace:
        meta["namespace"] = namespace
    if labels:
        meta["labels"] = labels

    target = esx.ExternalSecretSpecTarget(
        name=target_name or name,
        creation_policy=_CREATION_POLICY[creation_policy] if creation_policy else None,
    )

    spec = esx.ExternalSecretSpec(
        refresh_interval=refresh,
        secret_store_ref=esx.ExternalSecretSpecSecretStoreRef(
            name=store[0], kind=_STORE_KIND[store[1]]
        ),
        target=target,
        data_from=(
            [
                esx.ExternalSecretSpecDataFrom(
                    extract=esx.ExternalSecretSpecDataFromExtract(key=extract)
                )
            ]
            if extract is not None
            else None
        ),
        data=(
            [
                esx.ExternalSecretSpecData(
                    secret_key=d.secret_key,
                    remote_ref=esx.ExternalSecretSpecDataRemoteRef(
                        key=d.key, property=d.property
                    ),
                )
                for d in data
            ]
            if data is not None
            else None
        ),
    )
    return esx.ExternalSecret(scope, id, metadata=meta, spec=spec)
