"""External Secrets Operator CR builders.

cdk8s *emits the CRs*; ESO does the materialization. ExternalSecret is emitted
via the **typed** construct generated by `cdk8s import` from the vendored CRD
(imports.io.external_secrets) — see cdk8s.yaml. Three ExternalSecret shapes
appear in the legacy manifests, all covered here:

  1. `dataFrom.extract`  — pull every top-level key of a JSON SM value into the
     Secret (grafana OTLP, sentry, postgres). `extract=<sm key>`.
  2. per-key `remoteRef` + `property` — map specific SM JSON properties to named
     Secret keys (cert-manager creds). `data=[ESData(secret_key, key, property)]`.
  3. bare `remoteRef` — one SM container → one Secret key (obs stream-key).
     `data=[ESData(secret_key, key)]`.

SecretStore stays a `cdk8s.ApiObject`: its CRD bundles every ESO provider and one
(`keepersecurity.getByTitleFallback`) trips jsii's getXxx-name check, so the CRD
can't be imported. We only use the AWS provider and emit one SecretStore, so the
untyped path costs little — see cdk8s.yaml's import note.

The keybase `eso-aws-credentials` bootstrap is unchanged — cdk8s never creates
it; the SecretStore just references it, exactly as the legacy SecretStore did.
"""

from __future__ import annotations

from dataclasses import dataclass

import cdk8s
from constructs import Construct

import imports.io.external_secrets as esx

# The store every app ExternalSecret references — namespaced, identical in
# every env (isolation is structural: a namespaced store is unreachable
# cross-namespace; the backing eso-aws-credentials decides the AWS account).
DEFAULT_STORE = ("aws-secretsmanager", "SecretStore")

_STORE_KIND = {
    "SecretStore": esx.ExternalSecretSpecSecretStoreRefKind.SECRET_STORE,
    "ClusterSecretStore": esx.ExternalSecretSpecSecretStoreRefKind.CLUSTER_SECRET_STORE,
}
_CREATION_POLICY = {
    "Owner": esx.ExternalSecretSpecTargetCreationPolicy.OWNER,
    "Merge": esx.ExternalSecretSpecTargetCreationPolicy.MERGE,
    "None": esx.ExternalSecretSpecTargetCreationPolicy.NONE,
    "Orphan": esx.ExternalSecretSpecTargetCreationPolicy.ORPHAN,
}


@dataclass(frozen=True)
class ESData:
    """One entry in an ExternalSecret `spec.data[]`."""

    secret_key: str  # key in the materialized Secret
    key: str  # SM container path
    property: str | None = None  # JSON property within the SM value (pattern 2)


def secret_store(
    scope: Construct, id: str = "secret-store", *, namespace: str | None = None
):
    """Per-namespace `aws-secretsmanager` SecretStore. Byte-identical across
    envs (the in-namespace eso-aws-credentials routes to the right account)."""
    store = cdk8s.ApiObject(
        scope,
        id,
        api_version="external-secrets.io/v1",
        kind="SecretStore",
        metadata={
            "name": "aws-secretsmanager",
            **({"namespace": namespace} if namespace else {}),
        },
    )
    store.add_json_patch(
        cdk8s.JsonPatch.add(
            "/spec",
            {
                "provider": {
                    "aws": {
                        "service": "SecretsManager",
                        "region": "us-east-1",
                        "auth": {
                            "secretRef": {
                                "accessKeyIDSecretRef": {
                                    "name": "eso-aws-credentials",
                                    "key": "AWS_ACCESS_KEY_ID",
                                },
                                "secretAccessKeySecretRef": {
                                    "name": "eso-aws-credentials",
                                    "key": "AWS_SECRET_ACCESS_KEY",
                                },
                            }
                        },
                    }
                },
            },
        )
    )
    return store


def external_secret(
    scope: Construct,
    id: str,
    *,
    name: str,
    namespace: str | None = None,
    refresh: str = "1h",
    store: tuple[str, str] = DEFAULT_STORE,
    target_name: str | None = None,
    creation_policy: str | None = None,
    labels: dict[str, str] | None = None,
    extract: str | None = None,
    data: list[ESData] | None = None,
):
    """Emit one ExternalSecret (typed construct). Supply exactly one of `extract`
    (pattern 1) or `data` (patterns 2/3). `target_name` defaults to `name`."""
    if (extract is None) == (data is None):
        raise ValueError("external_secret: pass exactly one of extract= or data=")

    meta: dict = {"name": name}
    if namespace:
        meta["namespace"] = namespace
    if labels:
        meta["labels"] = labels

    target = esx.ExternalSecretSpecTarget(
        name=target_name or name,
        creation_policy=_CREATION_POLICY[creation_policy] if creation_policy else None,
    )

    spec = esx.ExternalSecretSpec(
        refresh_interval=refresh,
        secret_store_ref=esx.ExternalSecretSpecSecretStoreRef(
            name=store[0], kind=_STORE_KIND[store[1]]
        ),
        target=target,
        data_from=(
            [
                esx.ExternalSecretSpecDataFrom(
                    extract=esx.ExternalSecretSpecDataFromExtract(key=extract)
                )
            ]
            if extract is not None
            else None
        ),
        data=(
            [
                esx.ExternalSecretSpecData(
                    secret_key=d.secret_key,
                    remote_ref=esx.ExternalSecretSpecDataRemoteRef(
                        key=d.key, property=d.property
                    ),
                )
                for d in data
            ]
            if data is not None
            else None
        ),
    )
    return esx.ExternalSecret(scope, id, metadata=meta, spec=spec)
