# https://github.com/hadolint/hadolint#configure
ignored:
  # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3008
  # Use WORKDIR to switch to a directory
  # disabled cause there are lots to change in Dockerfile.nvidia
  - DL3003
