---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-stage
data:
  env-stage: |
    ENV=stage
    READ_ONLY="false"
    VERBOSE="false"

    DASHCAM_DIR=/opt/data/Dashcam
    SCREENCAP_DIR=/opt/data/screencaps
    CROPPED_CORNERS_DIR=/opt/data/cropped-corners
    MAPS_OUTPUT_DIR=/opt/data/maps
    RUN_DIR=/opt/data/run

    CHANNEL_NAME="adanalife_staging"
    BOT_USERNAME="adanalife_staging"

    TWITCH_AUTH_TOKEN="" #TODO: turn into secret
    # get these here: https://dev.twitch.tv/dashboard/apps/create
    TWITCH_CLIENT_ID="" #TODO: turn into secret
    TWITCH_CLIENT_SECRET="" #TODO: turn into secret

    GOOGLE_APPLICATION_CREDENTIALS="/opt/tripbot/infra/tripbot-stage.json"
    GOOGLE_APPS_PROJECT_ID="tripbot-stage"
    GOOGLE_MAPS_API_KEY="" #TODO: turn into secret

    DATABASE_HOST="localhost"
    DATABASE_USER="tripbot_dev"
    DATABASE_PASS="markka.ada.ester.alarmist" #TODO: turn into secret
    DATABASE_DB="tripbot_dev"

    TWILIO_ACCT_SID="" #TODO: turn into secret
    TWILIO_AUTH_TOKEN="" #TODO: turn into secret
    TWILIO_FROM_NUM="" #TODO: turn into secret
    TWILIO_TO_NUM="" #TODO: turn into secret

    SENTRY_DSN=""
    SENTRY_ENVIRONMENT="staging"

    DISABLE_TWITCH_WEBHOOKS="true"
    DISABLE_MUSIC_AUTOPLAY="true"

    EXTERNAL_URL="https://tripbot.dana.lol:3458"
    TRIPBOT_HTTP_AUTH="" #TODO: turn into secret
    TRIPBOT_SERVER_PORT="8082"
    VLC_SERVER_PORT="8090"
    VLC_SERVER_HOST=http://localhost
    MPD_SERVER_HOST=localhost:6600
