---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-dotenv
data:
  stage-dotenv: |
    ENV=stage

    EXTERNAL_URL="https://tripbot.dana.lol:3458"

    GOOGLE_APPS_PROJECT_ID="tripbot-stage"

    SENTRY_ENVIRONMENT="staging"

    DISABLE_TWITCH_WEBHOOKS="true"
    DISABLE_MUSIC_AUTOPLAY="true"
    READ_ONLY="false"
    VERBOSE="false"
