---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripbot
spec:
  template:
    spec:
      containers:

      - name: tripbot
        imagePullPolicy: Always
        command:
         - bash
        args:
         - -c
         - ls -al /opt/tripbot/assets && ls /opt/tripbot/assets/video && go run cmd/tripbot/tripbot.go 2>&1
        env:
         - name: ENV
           value: "stage"
         - name: VLC_SERVER_HOST
           value: "http://localhost"
         - name: MPD_SERVER_HOST
           value: "localhost:6600"

        volumeMounts:
        # mount stage-dotenv volume to /opt/tripbot
        - mountPath: /opt/tripbot/.env.staging
          readOnly: true
          subPath: .env.staging
          name: stage-dotenv
        - mountPath: /opt/tripbot/log
          name: log

      volumes:
      - name: stage-dotenv
        configMap:
          name: stage-dotenv
          items:
            - key: stage-dotenv
              path: .env.staging
      - name: log
        emptyDir: {}
