---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dashcam-from-host
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    # this is the path on the k8s worker that will
    # be shared to the container
    path: "/video"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashcam-from-host-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
