---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-dotenv
data:
  prod-dotenv: |
    ENV=prod

    EXTERNAL_URL="https://tripbot.dana.lol:3456" # shadyglen void

    DATABASE_DB=tripbot_prod

    GOOGLE_APPS_PROJECT_ID="tripbot-prod"
    GOOGLE_APPLICATION_CREDENTIALS="/opt/tripbot/infra/google/tripbot.json"

    SENTRY_ENVIRONMENT="production"

    DISABLE_TWITCH_WEBHOOKS="true"
    READ_ONLY="false"
    VERBOSE="false"
