---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripbot
spec:
  template:
    spec:
      containers:

      - name: tripbot
        imagePullPolicy: Always
        command:
         - bash
        args:
         - -c
         - go run cmd/tripbot/tripbot.go 2>&1
        env:
         - name: ENV
           value: "production"
         - name: VLC_SERVER_HOST
           value: "10.4.20.195:8088" # stream server's VLC
         - name: MPD_SERVER_HOST
           value: "10.4.20.195:6600"
         - name: DATABASE_HOST
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: DATABASE_HOST
         - name: DATABASE_PASS
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: DATABASE_PASS
         - name: TWITCH_CLIENT_ID
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWITCH_CLIENT_ID
         - name: TWITCH_CLIENT_SECRET
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWITCH_CLIENT_SECRET
         - name: TWITCH_AUTH_TOKEN
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWITCH_AUTH_TOKEN
         - name: SENTRY_DSN
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: SENTRY_DSN
         - name: TRIPBOT_HTTP_AUTH
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TRIPBOT_HTTP_AUTH
         - name: TWILIO_AUTH_TOKEN
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWILIO_AUTH_TOKEN
         - name: TWILIO_FROM_NUM
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWILIO_FROM_NUM
         - name: TWILIO_TO_NUM
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWILIO_TO_NUM
         - name: TWILIO_ACCT_SID
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: TWILIO_ACCT_SID
         - name: GOOGLE_MAPS_API_KEY
           valueFrom:
             secretKeyRef:
               name: tripbot-secrets
               key: GOOGLE_MAPS_API_KEY

        volumeMounts:
        # mount dashcam folder
        #TODO: does tripbot really need access to this?
        - name: dashcam-volume
          mountPath: /opt/data/Dashcam
          readOnly: true
        # mount prod-dotenv volume to /opt/tripbot
        - name: prod-dotenv
          mountPath: /opt/tripbot/.env.production
          readOnly: true
          subPath: .env.production
        # mount google-creds secret
        - name: google-creds
          mountPath: /opt/tripbot/infra/google
          readOnly: true
        - name: log
          mountPath: /opt/tripbot/log

      volumes:
      - name: dashcam-volume
        persistentVolumeClaim:
          claimName: dashcam-from-host-claim
      - name: prod-dotenv
        configMap:
          name: prod-dotenv
          items:
            - key: prod-dotenv
              path: .env.production
      - name: google-creds
        secret:
          secretName: google-creds
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: virtualhost.conf
              path: virtualhost/virtualhost.conf # dig directory
      - name: log
        emptyDir: {}
