before:
  hooks:
    - go mod download
builds:
  - env:
      # goreleaser does not support CGO
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - dockerfile: infra/docker/tripbot/Dockerfile
    image_templates:
    - "adanalife/tripbot:{{ .Tag }}"
    - "adanalife/tripbot:v{{ .Major }}"
    - "adanalife/tripbot:v{{ .Major }}.{{ .Minor }}"
    - "adanalife/tripbot:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
