version: '3.7'

services:
  tripbot:
    env_file:
      - cmd/tripbot/env.docker
    build:
      context: .
      dockerfile: cmd/tripbot/Dockerfile
    depends_on:
      - db
      # - mpd
    ports:
      # this should match the TRIPBOT_SERVER_PORT env var
      - "8080"
    volumes:
      - assets/video:/danalol/Dashcam/_all
      # - .env.development:/go/src/github.com/dmerrick/danalol-stream/.env.development
      # - /Volumes/usbshare1/cropped-corners:/danalol/cropped-corners
      # - /Volumes/usbshare1/maps:/danalol/maps

  #TODO: change credentials
  #TODO: share data volume
  db:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: tripbot_dev

  #TODO: get this working
  # mpd:
  #   image: vimagick/mpd
  #   ports:
  #     - "6600:6600"
  #     # - "8800:8800"
  #   # volumes:
  #   #   - ./mpd.conf:/etc/mpd.conf
  #   #   - ./music:/var/lib/mpd/music
  #   #   - ./playlists:/var/lib/mpd/playlists
  #   # devices:
  #   #   - /dev/snd
  #   # depends_on:
  #   #   - icecast
  #   restart: unless-stopped
