name: Bump Version & Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump-version
      uses: anothrNick/github-tag-action@1.37.0
      env:
        GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
    - uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.15
    - name: Create a Tripbot release
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist
        workdir: cmd/tripbot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      with:
        environment: production
        version: ${{ steps.bump-version.outputs.tag }}
        projects: tripbot vlc-server
