---
name: Super Linter

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run-linters
        uses: github/super-linter@v3
        env:
          # allow failures for the time being
          # DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_BASH: true
          DISABLE_DOCKERFILE: true
          DISABLE_DOCKERFILE_HADOLINT: true
          DISABLE_GO: true
          DISABLE_KUBERNETES_KUBEVAL: true
          DISABLE_MARKDOWN: true
