---
name: Super Linter

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libtesseract-dev tesseract-ocr
      - name: run-linters
        uses: github/super-linter@v3
        env:
          # allow failures for the time being
          # DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # disabled because it's not working with C libs
          VALIDATE_GO: false
          # disabled cause there are lots to change in Dockerfile.nvidia
          VALIDATE_DOCKERFILE_HADOLINT: false
          # disabled cause they dont support CRDs rn
          VALIDATE_KUBERNETES_KUBEVAL: false
