name: Create Release

on:
  pull_request:
  push:
    # tags:
    #   - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: release-tripbot
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
          workdir: cmd/tripbot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # disabled cause vlc-server needs CGO
      # - name: release-vlc-server
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     args: release --rm-dist
      #     workdir: cmd/vlc-server
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
