name: Create Release

on:
  # create a "snapshot" release for PRs
  pull_request:
  # create a version release when new tags are created
  push:
    tags:
      - v*

jobs:
  release-tripbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Release Tripbot
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
          workdir: cmd/tripbot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
