name: Testing
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

env:
  ENV: test
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Golang
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: Restore Cache
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install Dependencies (linux)
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y --no-install-recommends libvlc-dev
    - name: Run Go Tests
      run: go test -v -race ./...
    - name: Generate Coverage
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
