name: Testing
on: [push]
env:
  ENV: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Golang
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Source Code
      uses: actions/checkout@v2
    - name: Restore Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install Dependencies (linux)
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y --no-install-recommends tesseract-ocr libtesseract-dev libvlc-dev
    - name: Run Go Tests
      run: go test ./...
    - name: Increment Semantic Version
      id: version_bump
      uses: christian-draeger/increment-semantic-version@1.0.1
      with:
        current-version: '1.0.0'
        version-fragment: 'bug'
    #TODO: tag the release with this on merge?
    - name: Print Next Version
      run: echo ${{ steps.version_bump.outputs.next-version }}
