// The external test package (contract_test, not contract) is load-bearing:
// pkg/chatbot reaches pkg/contract transitively, so an in-package test
// importing it would be an import cycle. Testing from outside keeps the
// generated file guarded without pkg/contract itself ever importing the
// chatbot — the same boundary the reflection tests keep for the wire schemas.
package contract_test

import (
	_ "embed"
	"testing"

	"github.com/adanalife/tripbot/pkg/chatbot"
)

//go:embed chat-commands.json
var committedChatCommands []byte

// TestChatCommandsMatchesCommitted is the anti-drift guard for the chat command
// registry: it regenerates chat-commands.json from the live registry in
// pkg/chatbot and asserts the result is byte-identical to the committed file.
// Adding a command, renaming a trigger, changing an access gate, or moving a
// platform's command scope all change the generated bytes, so any of them fails
// here until the file is regenerated.
func TestChatCommandsMatchesCommitted(t *testing.T) {
	got, err := chatbot.MarshalChatCommands()
	if err != nil {
		t.Fatalf("MarshalChatCommands: %v", err)
	}
	if string(got) != string(committedChatCommands) {
		t.Errorf("chat-commands.json is out of date with pkg/chatbot's command registry.\n"+
			"Run `go generate ./pkg/contract` and commit the result.\n\n"+
			"--- committed chat-commands.json ---\n%s\n--- generated ---\n%s",
			committedChatCommands, got)
	}
}
